### ISSUE TITLE
Configure distance between Icon and Text

### ISSUE THREAD

**Issue by yjeroen** [zeel01/pin-fixer#13]
Would be great to be able to configure this distance, as with smaller textsizes, the text is quite far away from the Journal Note Icon.

**Comment by zeel01** [comment]
So I took a look at how this is controlled, and unfortunately it's not good news. 

```js
  /**
   * Draw the map note Tooltip as a Text object
   * @returns {PIXI.Text}
   * @protected
   */
  _drawTooltip() {

    // Create the Text object
    const textStyle = this._getTextStyle();
    const text = new PreciseText(this.text, textStyle);
    text.visible = false;
    const halfPad = (0.5 * this.size) + 12;

    // Configure Text position
    switch ( this.data.textAnchor ) {
      case CONST.TEXT_ANCHOR_POINTS.CENTER:
        text.anchor.set(0.5, 0.5);
        text.position.set(0, 0);
        break;
      case CONST.TEXT_ANCHOR_POINTS.BOTTOM:
        text.anchor.set(0.5, 0);
        text.position.set(0, halfPad);
        break;
      case CONST.TEXT_ANCHOR_POINTS.TOP:
        text.anchor.set(0.5, 1);
        text.position.set(0, -halfPad);
        break;
      case CONST.TEXT_ANCHOR_POINTS.LEFT:
        text.anchor.set(1, 0.5);
        text.position.set(-halfPad, 0);
        break;
      case CONST.TEXT_ANCHOR_POINTS.RIGHT:
        text.anchor.set(0, 0.5);
        text.position.set(halfPad, 0);
        break;
    }
    return text;
  }
```

Specifically `const halfPad = (0.5 * this.size) + 12;`: That `+ 12` at the end controls the space between the icon and text. In order to modify this value, the ` _drawTooltip()` method would need to be overridden.

Doing this isn't hard, but it is out of scope for what I want in this module. I would need to add a dependency on `lib-wrapper` to replace this method with a new version that used a configurable value there. I don't want to add a dependency to pin-fixer though.

That being said, this aught to be a relatively easy thing to change. You might want to open a feature request for Core, or see if another map note related module might already be doing something similar or in a similar area.

**Comment by zeel01** [comment]
One *could* in theory, but you would still need to wrapper this method to do so. And it has to be this method, since `_drawControlIcon()` which is called right before it uses that value to size the icon.
